---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tgenafricaco/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f styles.css $DEPLOYPATH
    - /bin/cp -f script.js $DEPLOYPATH
    - /bin/cp -f mobile.html $DEPLOYPATH
    - /bin/cp -f mobile.css $DEPLOYPATH
    - /bin/cp -f site.webmanifest $DEPLOYPATH
    - /bin/cp -f favicon.ico $DEPLOYPATH
    - /bin/cp -Rf assets $DEPLOYPATH
